# Generated by Django 4.2.1 on 2023-06-05 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoesMarket', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoesmodel',
            old_name='discpunt',
            new_name='discount',
        ),
        migrations.AlterField(
            model_name='commentmodel',
            name='like',
            field=models.BooleanField(help_text='Yes means you liked the shoes and No means you did not lik the shoes.', null=True),
        ),
        migrations.AlterField(
            model_name='commentmodel',
            name='title',
            field=models.CharField(blank=True, max_length=50, verbose_name='title'),
        ),
    ]
